language: node_js
node_js:
  - "4.0"
  - "5.0"
  - "6.0"
before_install:
  - npm install -g npm@3
install:
  - NODE_ENV=test npm install
matrix:
  include:
    - node_js: "8.0"
      env: PERFORM_LINT=1
script: ([ -z "$PERFORM_LINT" ] || npm run lint) && npm run test-karma
